### ISSUE TITLE
Problem with saving credentials into gradle.properties file

### ISSUE THREAD

**Issue by toantran-ea** [futurice/android-best-practices#106]
https://github.com/futurice/android-best-practices#gradle-configuration

For this part, when our project needs to be running on Continuous Integration server, which is automatically pulling code from Github, we need to be able to get those `fake/dummy` credentials to run the tests.

Is that better if you place all these credentials into `Environment Variables` list and export them accordingly when you're in your local machine or running them on CI servers.

**Comment by peter-tackage** [comment]
I'm quite open to suggestion on this matter. Personally, using non-CSV'd Gradle properties files to hold such sensitive keys seems adequate at best for development builds. If nothing else, at least it's platform independent. For CI systems, there's evidently a few options depending on the CI system being used (for e.g. Travis provides multiple options: https://docs.travis-ci.com/user/environment-variables/). 

I would be interested to hear how other people are tackling this.

**Comment by peter-tackage** [comment]
We use secret environment variables in Travis-CI to achieve this on https://github.com/futurice/freesound-android
