### ISSUE TITLE
Good practice on data set structuring

### ISSUE THREAD

**Issue by aimanbaharum** [futurice/android-best-practices#108]
Hi, can anyone advise on how to create a good data set to be passed in the **Adapter** for View creation, like **RecyclerView**?

For instance, if we want to build a complex RecyclerView layout, how would the data set should look like in JSON. I know it is as simple as passing a Collection with multiple model classes and let the Adapter create the ViewType, but I'd like to know what are the best practices in doing this, scalability and performance wise.

Also, is it a good practice to pass multiple data set into an Adapter?

Thanks

**Comment by peter-tackage** [comment]
In terms of passing a dataset to an Adapter, you should not be concerned with how it looks in JSON. Best practices would involve decoupling the JSON representation from the model representation used elsewhere in the app. 

Ideally, the model representation you give to the Adapter would require little to no additional manipulation before being applied to View. Any calculations or computation should be performed in a separate thread prior being supplied to the Adapter as a Collection (to avoid the datasetChanged overhead). Using ViewHolders (View recycling) is also an important part of creating a performant List UI - fortunately, this is what the RecyclerView was built for!
