### ISSUE TITLE
Reconsiderations in testing section

### ISSUE THREAD

**Issue by mehrdaad** [futurice/android-best-practices#113]
Thanks for providing this comprehensive guide.  
I think that testing sections should go under a heavy reconsideration.  
Android testing support library brings some testing frameworks (like espresso) which changes the way we develop our softwares.   
Not to mention special Junit runner for android and Instrumented tests.
Also I think Mockito and Hamcrest libraries should have been mentioned too.  
Tnx.

**Comment by peter-tackage** [comment]
Definitely! We've had a few requests to update the testing section, so I'll close this issue and you can follow #114
