### ISSUE TITLE
socket connect time out?

### ISSUE THREAD

**Issue by lonely917** [futurice/android-best-practices#119]
i run the demo and it crashed after a while, not pulling the data successfully. Connecting failed should be considered ..? Btw, i used android studio to import the demo project, i found that  using 'robolectric' may have some conflict with android studio test, i didn't build successfully until i remove the compile test part.

**Comment by peter-tackage** [comment]
Hi @lonely917. Thanks for the feedback. We're currently in the process of updating the demo project. I would consider it deprecated for now, given the number of Android Gradle plugin and Android Studio releases since it was originally created.
