### ISSUE TITLE
Genymotion advice is out of date

### ISSUE THREAD

**Issue by davidwhitman** [futurice/android-best-practices#131]
While it's true that Genymotion offers more features than the stock Android emulator, it's no longer significantly faster. 

If you can live without the extra Genymotion features, you don't need to pay the Genymotion subscription fee.

**Comment by gfreivasc** [comment]
The stock emulator is even faster since SDK Tools 25.3.1. I don't see why Genymotion would still be necessary

**Comment by peter-tackage** [comment]
See #139
