### ISSUE TITLE
Project structure: by-type vs. by-feature

### ISSUE THREAD

**Issue by FireZenk** [futurice/android-best-practices#133]
In my current projects I always choose _by feature_ project structure grouping like

- features
- - home
- - - HomeView
- - - HomePresenter
- - - HomeAdapter
- - detail
- - etc
- utils

But in your recommendation you only mention _by type_ and for clean code architectures is not clean at all, so I propose to add _by feature_ project structure recommendation
This is specially useful for MV* projects

**Comment by peter-tackage** [comment]
I was just thinking about how the documentation doesn't reflect my current approach. I'm definitely onboard with feature based structure. 

With an app of any significant scale, having the Fragments, Activities and what-have-you for a feature distributed around the place makes for a very noisy crowded structure. 

My revised approach is shown in Freesound: https://github.com/futurice/freesound-android/tree/master/app/src/main/java/com/futurice/freesound. There's still room for refinement in areas, but it's an improvement.

**Comment by akiwarheit** [comment]
+1

There's a video in which uncle bob mentioned about the project structure should reflect what it's trying to do (e.g. feature) and not following the "default" project structure. He emphasized that a single glance at the project should be sufficient to determine what this system/app/project is all about.

Can't seem to find the video though. I'll try looking for it tomorrow.

**Comment by peter-tackage** [comment]
One thought/question I'd like to bring up about the feature based structure is; to what extent should the feature package be coupled to its presentation. For example, a search feature could be its own Activity, then after a redesign, it ends up being on the Main Activity. The search feature itself might not change so much, would it be better to separate these two concepts? Should there be an additional package structure which relates only to presentation/UI?

- features
- - search
- - - SearchView
- - - SearchPresenter
- - - SearchAdapter
- - detail
- - etc
- presentation
- - main
- - detail
- - search
- - etc
- <others>

Obviously the terminology is a little overloaded when using MVP and perhaps it could be simplified for UI which only has a single feature, but you get the idea.

I haven't tried this, so I can't say whether it would be practical or effective, but I think it sits a little better with me than calling "Home" a feature.

Thoughts?

**Comment by peter-tackage** [comment]
See #146

**Comment by peter-tackage** [comment]
I've merged changes to recommend using feature based packaging and why in #146.
