### ISSUE TITLE
Add CI Recommendations

### ISSUE THREAD

**Issue by peter-tackage** [futurice/android-best-practices#148]
What is our first choice CI for customer projects?

**Comment by joan-domingo** [comment]
I could mention some conclusions from my slides about hosted CI, but I'm not so familiar with the customer projects and maybe they use their own non-hosted CI.

**Comment by pedpess** [comment]
@joan-domingo I think ur talk would fit pretty much in here. However, I think we shouldn't recommend any CI tool and just point the benefits of using a CI tool and what checks we could make in an Android application e.g. lint, checkstyle, pr check with danger.

**Comment by joan-domingo** [comment]
please review #175

**Comment by joan-domingo** [comment]
Resolved by #175
