### ISSUE TITLE
Recommend sharing your IDE code formatters

### ISSUE THREAD

**Issue by peter-tackage** [futurice/android-best-practices#159]
- Do this for code formatting consistency.

**Comment by pedpess** [comment]
@peter-tackage What do you mean by that? Sharing how we format code e.g. 80 columns etc?

**Comment by peter-tackage** [comment]
In Android Studio you can export your code style, which can then be placed in a repo for the team to import and use.

**Comment by pedpess** [comment]
Oh yeah, we were talking about the same thing, it helps a lot when u start a project to have some sort of agreement about the style or stating to the team that there is one that should be used.

**Comment by peter-tackage** [comment]
We do this in Freesound: https://github.com/futurice/freesound-android/tree/master/ide/android-studio
