### ISSUE TITLE
Avoiding Guava

### ISSUE THREAD

**Issue by pimterry** [futurice/android-best-practices#26]
The guidelines say "avoid using the Guava library, since it contains over 13k methods", as part of the guidance for dealing with the dex method limitation.

While avoiding the method limits is definitely a useful point, I'm pretty suspect of Guava as an issue itself.

For starters, because it's so heavily used in the Android ecosystem already: http://www.appbrain.com/stats/libraries/details/guava/google-guava. It's in 6% of the 500 most downloaded apps, including Spotify, Tumblr, etc.

On top of that, I think Proguard will strip out any methods you don't end up actually using there, so you won't get all 13K methods anyway.

Is there something else I'm missing? It seems like largeish libraries (like Guava) shouldn't actually be an issue, it's more a problem you hit if your app itself grows too large.

Oh, and top of that you should probably put in a note about multi-dex now (or the reasons not to use that I guess, I don't know): http://developer.android.com/tools/building/multidex.html. As of very recently, Google now support building apps with multiple dex files, to solve this issue entirely (and a support library too, to backport that)

**Comment by jonikarppinen** [comment]
For what it's worth, admittedly there's no real consensus about Guava on Android among Futurice developers.

I for one used Guava in one of our customer projects and was completely happy with that choice (in that case the app was not huge so we were not close to 65k limit).

So I wouldn't use a statement as strong as "avoid Guava" myself, and *depending on the needs*, I'd consider using Guava also in the future, going multidex if necessary. (But if I'd be mostly using stuff like `Lists.newArrayList()`, that hardly justifies adding the lib. :-) )

> On top of that, I think Proguard will strip out any methods you don't end up actually using there

But you won't use ProGuard on e.g. debug builds, so you do need take take the largeish method count into consideration. Anyway, agreed that we should cover multidexing in the guide. (Maybe I'll do it if I find the time to look into it.)

**Comment by AlexanderKaraberov** [comment]
I agree with @pimterry that Guava is not an issue. It offers a lot of goodies, which simplify development. We have ProGuard and now Multidex support.
I posted a question more than two years ago on stackoverflow: http://stackoverflow.com/questions/14978699/is-it-a-good-idea-to-use-google-guava-library-for-android-development   about the same issue.

**Comment by peter-tackage** [comment]
I've didn't really see the value in Guava, given the pressure it put on method limits. However, a few months back I saw a talk that demoed an app that showed it's strengths and I was fairly impressed. I think the key is that if you use Guava, use it thoroughly and get real value from it; it's a good, reliable library. 

With the somewhat recent modularization of Google Play Services, the pressure on method limits has eased somewhat, making the benefits of using Guava less of a trade-off.

**Comment by peter-tackage** [comment]
Closing this discussion due to inactivity.
