### ISSUE TITLE
Project template example for ListViews and slightly more complicated views than TextView

### ISSUE THREAD

**Issue by kaushikgopal** [futurice/android-best-practices#28]
The project template shows by way of the `SubscriptionUtils` class how one could bind data to a TextView. 

I'm curious to see how you use this similar approach with list views, adapters and the view model. Do you use the subjects to publish results, and as the results are published, add them as single items to the list adapter?

Alternatively, do you publish a chunk of results for the list, and just set the items on the adapter with one swoop?

**Comment by peter-tackage** [comment]
RxJava patterns have been explored in-depth elsewhere since this issue was originally opened, but hopefully the RecyclerView and SearchView example in this project https://github.com/futurice/freesound-android provide sufficient examples of an approach that was worked well for us.
