### ISSUE TITLE
Project templates

### ISSUE THREAD

**Issue by staltz** [futurice/android-best-practices#3]
We currently have the branch templates which is getting ready with one template. As the name suggests, it will be a directory with templates (plural), more than one.

Currently we are making one template based on RxJava, inspired by Timo Tuominen's Rx Android architecture. But since RxJava is not everyone's cup of tea, we should also have templates without it.

There is also the Retrofit vs Volley dichotomy. I can see at least 3 strong and good project templates we should have:

- RxJava + Retrofit + OkHttp + Picasso + Jackson
- Retrofit + OkHttp + Picasso + Jackson
- Volley + Jackson

We would some volunteer to guide the way with Volley, because at least I have no experience enough to be able to say "this is how you're supposed to use it".

**Comment by peter-tackage** [comment]
Closing. I can't see or imagine much movement on this issue. At least internally, https://github.com/futurice/freesound-android while not strictly being a template, provides a useful initial outline of a project structure that hopefully is useful to developers in the same way (assuming they are comfortable with Rx).
