### ISSUE TITLE
Espresso

### ISSUE THREAD

**Issue by logcat** [futurice/android-best-practices#56]
Hello

Espresso (https://code.google.com/p/android-test-kit/) is not mentioned at all. Did you have any bad experience with it?

**Comment by staltz** [comment]
Thanks for bringing this up! We were not so aware of Espresso before, but now that you mentioned it, looks very useful!

**Comment by logcat** [comment]
Unfortunately I did not use it heavily, so my opinions about it will be purely theorycraft. Espresso was discussed today at ADB podcast (there are also relevant links) http://androidbackstage.blogspot.fi/2015/04/episode-25-espresso.html

**Comment by benjamin-bader** [comment]
:+1: for Espresso.  Great for larger-scale integration tests.

**Comment by tomkoptel** [comment]
Espresso is the great tool better than Robotium (IMHO). 

By the way, there is exist interesting extension for espresso on the basis of RxJava - [RxPresso](https://github.com/novoda/rxpresso).

**Comment by peter-tackage** [comment]
Progressing under #114
