### ISSUE TITLE
Services, package location recommendations ?

### ISSUE THREAD

**Issue by binarysqueeze** [futurice/android-best-practices#59]
Using the package structure outlined in the document, what would be the recommended location for services ?

Its not really part of the view. 

Create a pacakge under root called services ?

**Comment by peter-tackage** [comment]
I agree, "services" at root level would be consistent with our recommendations. Of course, there's always an element of flexibility with the package naming conventions, depending on what best suits the app being developed and its architecture.

**Comment by iangregson-raet** [comment]
Great, thanks for your comments.

**Comment by binarysqueeze** [comment]
Great, thanks for your comments.
