### ISSUE TITLE
Auto increment or revision numbers

### ISSUE THREAD

**Issue by tomkoptel** [futurice/android-best-practices#63]
Hello folks,

I am wondering what is the best practice to handle auto incrementation approach for your builds?
So far I am using approach of generating dynamic version names and code like this:
```groovy
    android {
        defaultConfig {
            versionName = calculateVersionName()
            versionCode = calculateVersionCode()
        }
    }
    ext.calculateVersionName = {}
    ext.calculateVersionCode= {}
```
Inside project, I am storing `version.properties` file which is dynamically updated by script.
It basically looks like this:
```text
#Mon Jun 08 11:12:29 UTC 2015
major=2
revision=11
minor=1
patch=0
```
Basic implementation of calculate methods is following:
```groovy
Properties retrieveVersionProperties() {
    def properties = new Properties()
    def stream
    try {
        stream = new FileInputStream(versionFile)
        properties.load(stream)
    } catch (java.io.FileNotFoundException ignore) {
    } finally {
        if (stream != null) stream.close()
    }
    return properties
}

ext.calculateVersionName = {
    def version = retrieveVersionProperties()

    // safety defaults in case file missing
    if (!version['major']) version['major'] = "1"
    if (!version['minor']) version['minor'] = "0"
    if (!version['patch']) version['patch'] = "0"
    return "${major}.${minor}.${patch}"
}

ext.calculateVersionCode = {
    def version = retrieveVersionProperties()

    // safety defaults in case file missing
    if (!version['revision']) version['revision'] = "1"

    def code = 0
    code += Integer.valueOf(version['revision'])
    return code
}
```
So if I need to increment build I can simply update my `version.properties` file. Though I do not feel like this is the right way to handle auto increment.

Please, can you suggest me something elegant?

Cheers, Tom.

**Comment by peter-tackage** [comment]
There's many different possibilities for version numbering and auto-incrementing. Recently in my current project we've been using the Git commit hash, a bit like described in this [article](http://ryanharter.com/blog/2013/07/30/automatic-versioning-with-git-and-gradle/). This has worked quite well and you get auto-incrementing builds versions for free. Hopefully that helps!

**Comment by peter-tackage** [comment]
While not strictly related to auto-increment, I should point out that Jake Wharton's [U2020 demo app](https://github.com/JakeWharton/u2020/blob/master/build.gradle) provides some useful utility Gradle methods related to git commits and hashes.
