### ISSUE TITLE
Could fastjson be an alternative to JSON-POJO ?

### ISSUE THREAD

**Issue by LyndonChin** [futurice/android-best-practices#64]
I'm using [fastjson](https://github.com/alibaba/fastjson) in my project and it works well for no efficiency loss. 

This is the [benchmark](https://github.com/eishay/jvm-serializers/wiki)

**Comment by tomkoptel** [comment]
What about [Logan Square](https://github.com/bluelinelabs/LoganSquare) ?

This is the [benchmark](https://github.com/bluelinelabs/LoganSquare/blob/master/docs/benchmarks.jpg)

**Comment by peter-tackage** [comment]
There certainly is a lot of choice when it comes to JSON parsing/serialization for Java! I can also add Square's [Moshi](https://github.com/square/moshi) to the four others listed in our guide.

The key message from our advice is "avoiding reinventing the wheel". Unless you have a particularly good reason, manual handling of JSON is unnecessary, so employ a library that works well for you. Perhaps we've now come to the point where we are spoiled for choice? In regards to those specific libraries that you mentioned, we don't have any particular experience with them and have found Jackson or Gson sufficient.
