### ISSUE TITLE
Are new translations welcomed?

### ISSUE THREAD

**Issue by jonatasleon** [futurice/android-best-practices#67]
Currently I'm writing a translation of the README.md to portuguese. Could I create a pull request I when finish it?

**Comment by peter-tackage** [comment]
Hi @jonatasleon. New translations are most welcome! Just follow the structure of our other translations; https://github.com/futurice/android-best-practices/tree/master/translations and create a pull request so we can merge it once you are finished. Thanks for your interest!

**Comment by tremerhl** [comment]
Currently I'm writing README.md for Russian. I can also make one for Ukrainian if needed.

**Comment by djkalmyk** [comment]
Spasibo:)

**Comment by mike-stetsenko** [comment]
Translation into Russain published at habrahabr.ru on 23/07/2015: http://habrahabr.ru/post/262501

**Comment by tremerhl** [comment]
Created pull request with complete translation to Russian, including data storage section.

**Comment by mike-stetsenko** [comment]
@tremerhl Why don't you write the author about it? He'll be very pleased and fix mistakes at once.
Instead of this, you used his text and didn't inform him. Very nice

**Comment by tremerhl** [comment]
@mike-stetsenko  I didn't use that text to write my translation, but thank you for your advice. I will surely inform the author or article on habrahabr about his errors.

**Comment by mike-stetsenko** [comment]
@tremerhl OK :thumbsup:

**Comment by peter-tackage** [comment]
Closing this off. New and updated translations can be submitted through PRs.
