### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Suvitruf** [futurice/android-best-practices#69]
Hello. I just have some questions/remarks.

> Use Gradle and its recommended project structure

Why not Maven?
> Don't write your own HTTP client, use Volley or OkHttp libraries

Aquery, Android Asynchronous Http Client?
> Use the Jackson library to parse JSON data

Not GSON?
> Do not make a deep hierarchy of ViewGroups

Mb add some links, like [this](http://stackoverflow.com/a/9950339/1991579)

> There are two popular options: the old Ant & Eclipse ADT project structure, and the new Gradle & Android Studio project structure.

Maven & Eclipse?

> Always use ProGuard or DexGuard

Shrink? Penny-wise and pound-foolish. Obfuscate? Not sure. Is it always necessary?

**Comment by jonatasleon** [comment]
About JSON

> [...] Gson is a popular choice for solving this problem, however we find Jackson to be more performant since it supports alternative ways of processing JSON: streaming, in-memory tree model, and traditional JSON-POJO data binding. Keep in mind, though, that Jackson is a larger library than GSON, so depending on your case, you might prefer GSON to avoid 65k methods limitation.

**Comment by Suvitruf** [comment]
GSON also support: streaming, JSON-POJO and tree model...

**Comment by djodjoni** [comment]
IMHO Jackson is way too big for Android where GSON can do the same. (and performance nearly the same where GSON wins mostly)
Actually Android have native support for tree model and streaming.
For streaming native JsonReader
For thee model one can use the native JSONObject and JSONArray. 
Also for POJO there is a new kid in town which claims to be the fastest:
https://github.com/bluelinelabs/LoganSquare

**Comment by aziflaj** [comment]
I'd like to ask this about database stuff. Would you recommend writing a Content Provider or using an ORM?

**Comment by aziflaj** [comment]
NVM, I found issue #31

**Comment by castial** [comment]
About Gradle and Maven
>I I recommend reading the article from the Steve Ebersole. He is Hibernate Project Manager.  
[Gradle: why?](https://developer.jboss.org/wiki/Gradlewhy?_sscc=t)  

Maybe this's the reason why android studio recommend using Gradle.

**Comment by 31H0B1eV** [comment]
If you recomend use OkHttp, you already have Gson and this is not really good idea include Jakson in same project.

**Comment by peter-tackage** [comment]
@31H0B1eV OkHttp is a HTTP client, so it does not have any JSON (de)serialization responsibilities or a Gson dependency. You may be thinking of Retrofit, which is often used with OkHttp and a JSON library of your choosing.

**Comment by Suvitruf** [comment]
@peter-tackage in OkHttp .pom I see
```
      <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>${gson.version}</version>
      </dependency>
```

**Comment by peter-tackage** [comment]
I did a quick search for the usage of Gson in OkHttp and it appears that dependency is used for testing and samples, not the actual shipped artifact.

**Comment by 31H0B1eV** [comment]
Yep, sorry it's my mistake, i'm almost always use OkHttp with Retrofit, and was confused with it. But OkHttp + Retrofit is best way to make rest api calls and usually if you getting json, you working with rest. So i think that OkHttp + Retrofit must be a standart, and in this case gson is best choice, this what i mean.

**Comment by peter-tackage** [comment]
Why not Maven?

Gradle is the supported build system for Android, that alone is a very good reason to use it. The Android Gradle plugin is powerful and flexible with continual improvements with excellent IDE integration.  Although some have used Maven in the past, with Gradle now in the picture it arguably doesn't have much of a future on Android. That makes Gradle our recommended best practice.

    Don't write your own HTTP client, use Volley or OkHttp libraries

There are a lot of choices in this space, our recommendation to use Volley, OkHttp and Retrofit  based upon our own battle-harded use in apps. They are well designed, tested and proven libraries with great technical support and expertise in the wider Android community.

    Use the Jackson library to parse JSON data

Personally, I do use Gson as a part of the Retrofit + Gson + OkHttp stack. Ultimately, the advice to use Jackson should be read as "use a JSON parsing library"; don't perform unnecessary manual JSON parsing.

    Do not make a deep hierarchy of ViewGroups
    Mb add some links, like this

We link to some resources that provide some good info on the reasoning. In either case, I don't think too many people will disagree with this one.

    Maven & Eclipse?

Before the introduction of Android Studio and Gradle into the Android SDK environment we found using Eclipse and Maven a fairly frustrating experience. The new tooling makes for a much better, powerful experience that will continue to improve. Hopefully it's clear that no one should be using Eclipse anymore!

    Always use ProGuard or DexGuard
   Shrink? Penny-wise and pound-foolish. Obfuscate? Not sure. Is it always necessary?

For reasons of APK size and footprint, shrinking your app with Proguard is a good practice. The important caveat being that Proguard should be introduced early in the project and its configuration regularly exercised via builds. As you suggested earlier, being selective in your library choices to minimize the possibility of using multiple libraries that provide similar functionality (e.g. Picasso and Glide) is also an important part of this.

Obfuscation is not a silver bullet and some libraries make using it hard to configure. It's still a reasonable first defense and can often be a customer expectation. Again, testing your configuration early and often is important so it's best to start with it enabled.
