### ISSUE TITLE
The Robolectric Gradle plugin is deprecated

### ISSUE THREAD

**Issue by ilkka** [futurice/android-best-practices#77]
The new [getting started instructions for Robolectric](http://robolectric.org/getting-started/) have the details. The template project still uses the plugin.

**Comment by peter-tackage** [comment]
Hey, thanks for letting us know.

**Comment by peter-tackage** [comment]
@ilkka I would just say that we remove Roboletric from the template project. I wouldn't consider it a best practice.

**Comment by peter-tackage** [comment]
Progressing under #114
