### ISSUE TITLE
Writing strings in all uppercase

### ISSUE THREAD

**Issue by blipinsk** [futurice/android-best-practices#80]
>Don't write string values in all uppercase. Stick to normal text conventions (e.g., capitalize first character). If you need to display the string in all caps, then do that using for instance the attribute textAllCaps on a TextView.

I strongly disagree with that. Some devices (e.g. Samsung Galaxy Note 3 SM-N7505) do not really respect `textAllCaps` property of `TextViews`. So in order to make your app look exactly the same on all devices you SHOULD use string values in all uppercase.

**Comment by peter-tackage** [comment]
Hi @blipinsk, thanks for your input. 
I would consider the disregarding of ``textAllCaps`` by the Note 3 as buggy behavior and I would prefer to not let one (or a few) buggy devices dictate the general approach. To better handle this, I would propose -

- Use "natural" capitalization in the string resource definitions as described.
- Abstract the ``Resources:getString()`` method behind an interface.
- Inject an appropriate preprocessor into the implementations of the interface to modify capitalization depending on device (default is no-op). 

This would allow you to throw away specific workarounds if the buggy devices ever were fixed or were no longer a target device of your app.

"Don't let buggy devices dictate your general approach" - is something we should add to the guide.

**Comment by peter-tackage** [comment]
I should also add that appropriate capitalization of words can be quite specific to the languages being used. Unless the app design dictates that all caps be used (!), it's best to use the most natural form of the words in the resources to avoid possible unnatural wordings. For example, in German "GmbH" as an abbreviation for "Gesellschaft mit beschränkter Haftung" could look slightly odd as "GMBH".

**Comment by jush** [comment]
Be careful with using `textAllCaps`, it calls `toString()` and you might lose any formatting you might have set.
See [AllCapsTransformationMethod](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/text/method/AllCapsTransformationMethod.java#L59) which is used by `TextView`
