### ISSUE TITLE
String obfuscation?

### ISSUE THREAD

**Issue by acrolink** [futurice/android-best-practices#81]
Thank you very much for the valuable information available here. I have one question thought. Do you know of an obfuscator software (preferably open source) that is able to obfuscate strings inside Android's app class files?

I want to install an Android app on local devices and to write inside the code some credentials for Restful endpoint authentication. I want to make sure that the credentials won't be readable by reverse engineering. Any ideas? Thanks.

**Comment by tomkoptel** [comment]
Hello @acrolink ! 

Sorry for not pinpointing to the conrete solution, but the issue you are tackling can be resolved through the usage of the native code. The idea is to bundle your credentials inside native code that will be bind by JNI. This way you will ensure that strings won't be easily reverse engineered, as soon as they are part of binary files. Though, such approach complicates application code and requires from your side to build code for different platforms.

**Comment by peter-tackage** [comment]
You should keep in mind that ultimately, any credentials that you distribute are vulnerable to reverse engineering. Proxy tools such as [Charles](charlesproxy.com) can do this for HTTPS web traffic. So obfuscation in the APK only provides limited benefit.
