### ISSUE TITLE
Is the MVP architecture better than MVC?

### ISSUE THREAD

**Issue by santong** [futurice/android-best-practices#83]
Hi, I'm a beginner of Android and translating the doc to Chinese for few days since I noticed that you updated it. 

And I found a question when I translated this part https://github.com/futurice/android-best-practices#java-packages-architecture. 

I read some articles about the architecture of Android and found that more and more people suggest to use MVP architecture. So I wonder know if the MVC is still the best choice now?

**Comment by kaedea** [comment]
There is not clear MVC architecture in Android.

**Comment by santong** [comment]
Thanks for your answer.
Does it main there is no standard architecture in Android?

**Comment by tomkoptel** [comment]
Hello @santong !

So far "standard" architecture may be called MVP(Model View* Presenter). Where is View stands more for combination of contract interfaces which are also known as View Interfacces. Summing up, in android enviroment mentioned stack treated more as MViVP(Model View Interface View Presenter).

For more details take a look on [nice article](http://blog.sqisland.com/2015/11/mvp-missing-link.html) of @chiuki 

In her article she mentiones [Android lab](http://www.code-labs.io/codelabs/android-testing/#4) which in some extenct can be treated as suggested or, maybe, offiicial architecture for majority apps.

**Comment by santong** [comment]
@tomkoptel Thank you very much. It troubled me for a long time.

**Comment by johnwatsondev** [comment]
@tomkoptel Thanks for useful information!
