### ISSUE TITLE
关于使用maven依赖引入最新版这点不是很赞同。

### ISSUE THREAD

**Issue by SadieYuCN** [futurice/android-best-practices#88]
在实际的项目开发中遇到过使用 x.x.+在编译的时候引入了最新版本。由于新版的改动，而导致项目一些方法调用返回非预期，或者方法被弃用，新版库换了新的实现等一系列的问题。所以后来统一使用指定版本，了解新版特性后在决定要不要升级类库。

使用 Maven 依赖方案代替使用导入jar包方案 如果在你的项目中你明确使用率 jar文件，那么它们可能成为永久的版本，如2.1.1.下载jar包更新他们是很繁琐的， 这个问题Maven很好的解决了，这在Android Gradle构建中也是推荐的方法。你可 以指定版本的一个范围，如2.1.+,然后Maven会自动升级到制定的最新版本，例如：

dependencies {
    compile 'com.netflix.rxjava:rxjava-core:0.19.+'
    compile 'com.netflix.rxjava:rxjava-android:0.19.+'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.+'
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.+'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.4.+'
    compile 'com.squareup.okhttp:okhttp:2.0.+'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.+'
}

**Comment by liutingdu** [comment]
这里写了不推荐使用Maven自动引入新版本啊：

**Avoid Maven dynamic dependency resolution** Avoid the use of dynamically versioned, such as 2.1.+ as this may result in different and unstable builds or subtle, untracked differences in behavior between builds. The use of static versions such as 2.1.1 helps create a more stable, predictable and repeatable development environment.

**Comment by edhub** [comment]
经过实践，我也认为使用固定的版本会更好，理由如下：
一、动态版本有可能会引入未知的问题，虽然这个可能性很小
二、由于在国内，如果使用动态版本的话，每次在gradle在解析依赖关系的时候都会花非常多的时间。虽然设置离线模式可以解决这个问题，但还不如就用固定版本。

**Comment by peter-tackage** [comment]
I think we can close this now. Thanks for the discussion.
